# Generated by Django 4.2.13 on 2024-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code_id', models.TextField()),
                ('office_code_name', models.TextField()),
            ],
        ),
    ]
